services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cenarius_test

  cenarius:
    build: .
    ports:
      - "8080:8080"
    environment:
      CENARIUS_LOG_LEVEL: INFO
      CENARIUS_SERVER_BIND: ":8080"
      CENARIUS_DATABASEDSN: postgres://postgres:password@db:5432/cenarius_test?sslmode=disable
      CENARIUS_SECRET_STORAGE_PATH: /tmp
    depends_on:
      - db

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_cenarius.conf:/etc/nginx/conf.d/default.conf
      - ./cenarius.crt:/etc/nginx/ssl/cenarius.crt
      - ./cenarius.key:/etc/nginx/ssl/cenarius.key
    depends_on:
      - cenarius
