name: Test and coverage

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: cenarius_test
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.21'
      - name: Run coverage
        run: CENARIUS_DATABASEDSN="postgres://postgres:postgres@localhost:5432/cenarius_test?sslmode=disable" go test -race -coverprofile=coverage.out -covermode=atomic ./...
